[package]
name = "mpdtrackr"
authors = ["Cyanism"]
description = "A simple MPD tracker"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"] }
dirs = "*"
futures = "*"
json = "*"
mongodb = "*"
mpd = "*"
tokio = { version = "1.28.1", features = ["full"] }
